repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        args: [ --maxkb=560 ]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      # - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: fix-encoding-pragma
      - id: flake8
      - id: forbid-new-submodules
      - id: mixed-line-ending
      # - id: no-commit-to-branch
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.2
    hooks:
      # - id: git-check
      - id: git-dirty
      # - id: markdownlint
      # - id: shellcheck
      # - id: script-must-have-extension
      # - id: script-must-not-have-extension
      # - id: shfmt

  - repo: https://github.com/Lucas-C/pre-commit-hooks-go
    rev: v1.0.1
    hooks:
      - id: checkmake

  - repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.9
    hooks:
      - id: validate-html

  - repo: https://github.com/Lucas-C/pre-commit-hooks-lxml
    rev: v1.1.0
    hooks:
      - id: forbid-html-img-without-alt-text
      - id: forbid-non-std-html-attributes
      - id: detect-missing-css-classes
        args:
          - --css-files-dir
          - .
          - --html-files-dir
          - .
      - id: html-tags-blacklist
      - id: html-attributes-blacklist

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v1.0.0
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.5.2
    hooks:
      - id: check-autopkg-recipe-list
      - id: check-autopkg-recipes
      - id: check-jamf-extension-attributes
      - id: check-jamf-scripts
      - id: check-jamf-profiles
      - id: check-munki-pkgsinfo
      - id: check-munkiadmin-scripts
      - id: check-munkipkg-buildinfo
      - id: check-outset-scripts
      - id: check-plists
      - id: forbid-autopkg-overrides
      - id: forbid-autopkg-trust-info
      # - id: munki-makecatalogs

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v0.2.0
    hooks:
      #    - id: clang-format
      #      args: [--style=LLVM]
      # - id: clang-tidy
      #  args: [-checks=*, -warnings-as-errors=*]
      - id: oclint
        args: [-enable-clang-static-analyzer, -enable-global-analysis]
