language: csharp
sudo: required
mono: none

matrix:
  include:
  - os: linux
    dist: trusty # Ubuntu 14.04
    dotnet: 2.1.600
    mono: none
    env: DOTNETCORE=1
    sudo: required
  - os: osx
    osx_image: xcode9.4
    dotnet: 2.1.6ßß
    mono: none
    env: DOTNETCORE=1
    before_install:
      - chmod a+x ./runtests.sh
      ulimit -n 1024 ;
      brew update
      