language: csharp
sudo: required
mono: none

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

matrix:
  include:
    - os: linux
      dist: trusty # Ubuntu 14.04
      dotnet: 2.2.100
      mono: none
      env: DOTNETCORE=2
      sudo: required
    - os: osx
      dotnet: 2.2.100
      mono: none
      env: DOTNETCORE=2
      before_install:
        - chmod a+x ./runtests.sh
        - ulimit -n 1024 ;
        - brew update

before_install:
  - chmod a+x ./runtests.sh

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - export TRAVIS=1

script:
  - ./runtests.sh
