version: 0.3.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: dotnet restore ./src/jmbde/jmbde.csproj
test_script:
- cmd: dotnet test ./test/jmbde.Tests/jmbde.Tests.csproj
artifacts:
- path: \src\jmbde\packageoutput\jmbde\**\*.nupkg
  name: jmbde
deploy:
# master deployment to release
- provider: NuGet
  api_key:
    secure: jNtt/O0YdM+cKFiPbqv5EXIgbXlvGzXR45WLJdEWdhIwKTUCoGr44lmUkVY9xigd
  on:
    branch: master
  artifact: jmbde
- provider: NuGet
  api_key:
    secure: 8k6x/+D9myin3NcqvffoD/G3S02aNxY8cQpD3Yspu71V0jbnk1wajcsI8+KYN7Sh
- provider: GitHub
  tag: $(appveyor_build_version)
  release: $(appveyor_build_version)
  auth_token:
    secure: dgHvp6cRuN111wnt2rANR25qfklalE+m06hxhy7XbFRkoGjW46h9mu8wxqsaTPHj
  on:
    branch: master
  artifact: jmbde