name: CI on Branches and PRs

on:
  workflow_dispatch:
    branches: [master]
    paths: "src/**"
  push:
    branches: [master]
    paths: "src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Setup dotnet 5.XX sdk
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.103

      - name: Check dotnet sdk install
        run: dotnet --info

      - name: Install dependencies
        run: dotnet restore

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Display the version
        run: |
          echo "Version: ${{ steps.gitversion.outputs.semVer }}"
      - name: Build solution
        run: |
          dotnet build -p:Configuration=Release --no-restore -p:version=${{ steps.gitversion.outputs.semVer }}

      - name: Unit & integration test
        run: |
          dotnet test -p:Configuration=Release --no-restore -p:version=${{ steps.gitversion.outputs.semVer }}

      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuget-packages
          path: "**/*.nupkg"
      - name: Publish the package to NuGet.Org
        run: dotnet nuget push "**/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.PUBLISH_NUGET_ORG }} --skip-duplicate
