---
name: Release

on:
    push:
        tags:
            - '*'


env:
    RUN_ID: build.${{ GITHUB.RUN_ID }}
    RUN_NUMBER: build.${{ GITHUB.RUN_NUMBER }}
    SHA: ${{ GITHUB.SHA }}
    MYGET_API_TOKEN: ${{ SECRETS.MYGET_API_TOKEN }}
    GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}

jobs:
    check_commit_msg:
        outputs:
            commit_message: ${{ steps.get_message.outputs.message }}
        name: Check if the workflow has been disabled.
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Get commit message
              id: get_message
              run: |
                  echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.event.after }})"

    build:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Git fetch tags
              run: git fetch --tags

            - name: Check tags
              run: git tag -l -n

            - name: Setup dotnet 5.0.x sdk
              uses: actions/setup-dotnet@v1.7.2
              with:
                  dotnet-version: 5.0.103

            - name: Check dotnet sdk install
              run: dotnet --info

            - name: Install dependencies
              run: dotnet restore

            - name: Build solution
              run: dotnet build -c Release --no-restore

            - name: Test solution
              run: |
                dotnet tool update --global dotnet-ef
                dotnet ef database update --project src/jmbde
                dotnet test -c Release --no-build --no-restore --verbosity normal

            - name: Pack packages
              run: |
                  $LastTag =git describe --tags (git rev-list --tags --max-count=1)
                  echo "Last tag is: ${LastTag}"
                  $Version = ($LastTag).TrimStart('v').TrimEnd("beta").TrimEnd("preview")
                  echo "Publishing version: ${Version}"
                  $PackageVersion = ($LastTag).TrimStart('v') + "-" + $env:RUN_NUMBER + "." + $env:SHA.SubString(0, 7)
                  echo "Publishing package version: ${PackageVersion}"
                  dotnet pack -c Release -o packages /p:PackageVersion=$PackageVersion /p:Version=$Version --no-build
            - name: Publish artefacts
              uses: actions/upload-artifact@v2.2.2
              with:
                  name: "drop-ci-packages"
                  path: "./packages"
